blank_issues_enabled: false
contact_links:
  - name: 📖 Документация проекта
    url: https://github.com/Vladislav6410
    about: Ознакомься с документацией перед созданием задачи.
  - name: 🛠 Техническая поддержка
    url: https://t.me/WebKurierBot
    about: Задай вопрос напрямую через Telegram.
  - name: 🌐 WebKurier Docs
    url: https://webkurier.gitbook.io/docs
    about: Полная документация по системе и модулям.