/**
 * WebKurier Translator — Language Catalog
 * Goal: "all languages" UX without huge static lists.
 *
 * UI can generate localized labels using Intl.DisplayNames.
 * Here we define:
 *  - special "auto" (detect language)
 *  - recommended locales (language + region variants)
 *  - provider constraints (which codes are supported)
 */

export const AUTO = { code: "auto", labelKey: "Detect Language" };

// Minimal curated locales to match “country variants” UX (extend anytime)
export const RECOMMENDED_LOCALES = [
  // Core
  "en-US", "en-GB",
  "de-DE", "de-AT", "de-CH",
  "ru-RU", "uk-UA", "pl-PL",
  "es-ES", "es-MX", "es-US",
  "pt-PT", "pt-BR",
  "fr-FR", "fr-CA", "fr-CH",
  "it-IT", "nl-NL", "nl-BE",
  "sv-SE", "da-DK", "fi-FI", "no-NO",
  // Asia
  "zh-Hans", "zh-Hant", "zh-HK",
  "ja-JP", "ko-KR",
  // Middle East (examples)
  "ar-SA", "ar-AE", "ar-EG",
];

/**
 * Provider capability mapping.
 * Important: keep this separate from UI language list.
 * UI may show many locales, but provider may only accept base language ("de", "ru", etc.)
 */
export const PROVIDER_SUPPORT = {
  libretranslate: {
    acceptsLocales: false, // expects base language codes
    // keep it flexible: allow any ISO-639-1, but you can clamp if your LT instance is limited.
    allowAny639_1: true,
    hardAllowList: null, // or ["en","de","ru","uk","pl",...]
  },

  // Example for future router providers:
  openai: { acceptsLocales: true, allowAny639_1: true, hardAllowList: null },
  google: { acceptsLocales: true, allowAny639_1: true, hardAllowList: null },
};

/** Normalize locale/code to what provider expects */
export function normalizeLangForProvider(input, provider = "libretranslate") {
  if (!input) return "auto";
  if (input === "auto") return "auto";

  const p = PROVIDER_SUPPORT[provider] || PROVIDER_SUPPORT.libretranslate;

  // If provider doesn't accept locales, reduce "de-DE" -> "de"
  if (!p.acceptsLocales) return input.split("-")[0];

  return input; // keep locale
}

/**
 * UI helper: build a list of languages.
 * - recommendedLocales first
 * - then the rest can be generated by UI via search (by code)
 */
export function buildLanguageMenu() {
  return [AUTO, ...RECOMMENDED_LOCALES.map(code => ({ code }))];
}